# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20180328_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
